services:
  parser:
    container_name: vkparser
    image: spring-parser:latest
    build:
      context: ./spring_app/vkparser
      dockerfile: ${DOCKERFILE:-Dockerfile}
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:8080/health/ping || exit 1']
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 30s
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - mynetwork

  tg-bot:
    container_name: tg-bot
    image: tg-bot:latest
    build:
      context: ./python_app/vkparser
      dockerfile: ${DOCKERFILE:-Dockerfile}
    depends_on:
      parser:
        condition: service_healthy
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://parser:8080/health/ping || exit 1']
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 5s
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - mynetwork
  db:
    container_name: postgres
    image: postgres:16
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 15s
      timeout: 10s
      retries: 10
    env_file:
      - .env
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - '${NGINX_PORT}:${NGINX_PORT}'
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/templates/default.conf.template
    env_file:
      - .env
    depends_on:
      parser:
        condition: service_healthy
      tg-bot:
        condition: service_healthy
      db:
        condition: service_healthy
    networks:
      - mynetwork
  redis:
    container_name: redis
    image: redis:alpine
    volumes:
      - redis_data:/data
    env_file:
      - .env
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    networks:
      - mynetwork
volumes:
  db_data:
  redis_data:

networks:
  mynetwork:
    driver: bridge
