services:
  parser:
    image: spring-parser:latest
    build:
      context: ./spring_app/vkparser
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
      #redis todo
    ports:
      - '${APP_PORT}:${APP_PORT}'
    env_file:
      - .env
    networks:
      - mynetwork

  tg-bot:
    image: tg-bot:latest
    build:
      context: ./python_app/vkparser
      dockerfile: Dockerfile
    depends_on:
      - parser
    env_file:
      - .env
    networks:
      - mynetwork
  db:
    image: postgres:16
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_USER}']
      interval: 15s
      timeout: 10s
      retries: 10
    env_file:
      - .env
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - mynetwork
  # redis:
  #todo
volumes:
  db_data:

networks:
  mynetwork:
    driver: bridge
