FROM gradle:8.13.0-jdk23-alpine AS build

WORKDIR /app

COPY build.gradle settings.gradle ./
COPY gradle/ gradle/

RUN gradle dependencies --no-daemon

COPY . .

RUN gradle build -x test --no-daemon

FROM eclipse-temurin:23-jdk-alpine AS run

WORKDIR /app

RUN apk add curl

COPY --from=build /app/build/libs/*.jar app.jar

EXPOSE 8080

CMD ["java", "-jar", "app.jar"]
