FROM python:3.12-alpine

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

RUN apk add curl

EXPOSE 9090

CMD ["watchmedo", "auto-restart", "--directory=.", "--pattern=*.py", "--recursive", "--debug-force-polling", "--", "python", "run.py"]
