spring:
  application:
    name: Vk Parser
  devtools:
    restart:
      enabled: true
    liveReload:
      enabled: true
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create

springdoc:
  swagger-ui:
    enabled: true

    path: /api/v1/docs
  api-docs:
    enabled: true
    path: /api/v1/docs/api-docs

logging:
  level:
    sql: off
